# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source code and build files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional, MCP uses stdio by default)

# Command to run the MCP server
CMD ["node", "build/index.js"]
